### ISSUE TITLE
Can this method be used to do subgraph matching?

### ISSUE THREAD

**Issue by lihuiliullh** [mims-harvard/SubGNN#11]
A very nice paper. But can this method be used to do subgraph matching?

**Comment by EmilyAlsentzer** [comment]
The code can't do subgraph matching out of the box. Currently it's set up for subgraph classification. It assumes that you have prespecified subgraphs & associated labels that you want to predict.

However, the SubGNN architecture is generalizable and can be used for unsupervised or semi-supervised learning as well by changing the loss function. I can imagine using an approach like that used in [NeuroMatch](https://arxiv.org/pdf/2007.03092.pdf) to identify query subgraphs and then using SubGNN with a semi-supervised learning objective to embed the subgraphs.

Hope this helps!
