### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JhuoW** [mims-harvard/SubGNN#12]
I run train_config.py -config_path config_files/ppi_bp/ppi_bp_config.json. I got the following error:

![图片](https://user-images.githubusercontent.com/12757730/102893716-03d86680-449d-11eb-92c1-e4a4234fce8c.png)

Thanks

**Comment by EmilyAlsentzer** [comment]
Can you make sure you've pulled the most recent version of the code? It looks like that line is missing an `enumerate`. See [here](https://github.com/mims-harvard/SubGNN/blob/main/SubGNN/SubGNN.py#L802).

**Comment by JhuoW** [comment]
Thanks. I didn't use the latest code
