### ISSUE TITLE
Training the model over a networkx dataset

### ISSUE THREAD

**Issue by vapolonio** [mims-harvard/SubGNN#2]
Hi, I have a dataset of networkx objects with subgraph samples and a dataset of egonets in networkx format too. And I trying founds subgraphs for similarity in each egonet. Reading yours paper the problem seems to me a very similar and I'm try test your model for my context.  Can I use a dataset with networkx format for it? 

Thanks and congrats for the amazing work 😃

**Comment by EmilyAlsentzer** [comment]
Yes, to use your own data with SubGNN, you just need an edge list for your base graph and a text file that describes the subgraphs and their labels. See the [updated README](https://github.com/mims-harvard/SubGNN/tree/main/prepare_dataset#your-own-data) for instructions on how to format the data.

I'm closing the issue, but feel free to post another if you have any additional questions.
