### ISSUE TITLE
Data question

### ISSUE THREAD

**Issue by wangzeyu135798** [mims-harvard/SubGNN#3]
Hi:
    In the downloaded data, there is ego_graphs.txt. As the content in this txt file, is it each node's one ego_graphs?

**Comment by EmilyAlsentzer** [comment]
Yes, that's correct. It's a dictionary from node id to list of nodes in the 1-hop neighborhood of the node. Check out the script [precompute_graph_metrics.py](https://github.com/mims-harvard/SubGNN/blob/main/prepare_dataset/precompute_graph_metrics.py) to see how this is computed.
