### ISSUE TITLE
Similarities files

### ISSUE THREAD

**Issue by wangzeyu135798** [mims-harvard/SubGNN#4]
Hi:
    After downloading data, there are six .npy files in config_files/hpo_metab/similarities. I want to learn how to make them?

**Comment by EmilyAlsentzer** [comment]
Hi @wangzeyu135798, I just added the code to precompute pairwise shortest paths, ego graphs, and degrees. See the [README](https://github.com/mims-harvard/SubGNN/tree/main/prepare_dataset#prepare-data) for details. The `.npy` files in the similarities folder will be generated while running SubGNN if they do not exist (see `get_similarities` function [here](https://github.com/mims-harvard/SubGNN/blob/main/SubGNN/SubGNN.py#L836)). If they already exist, SubGNN will read them in from file. Hope this helps! Feel free to reopen the issue if you have additional questions.
