### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by wangzeyu135798** [mims-harvard/SubGNN#6]
Hi:
   In /SubGNN/subgraph_mpn.py, line 213
    mp_type = self.__get_mp_type__(edge_index)
    torch.nn.modules.module.ModuleAttributeError: 'SG_MPN' object has no attribute '__get_mp_type__'
    How to solve it?

**Comment by EmilyAlsentzer** [comment]
This function is from Pytorch Geometric. My guess is that this issue is due to a mismatch in Pytorch Geometric versions. Were you able to use the provided conda environment? If not, which version are you using?

**Comment by wangzeyu135798** [comment]
&nbsp; &nbsp; Thanks！I changed torch-geometric from 1.6.0 to 1.4.3, the code is ok in my device.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mims-harvard/SubGNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 凌晨2:30
收件人:&nbsp;"mims-harvard/SubGNN"<SubGNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mims-harvard/SubGNN] Code (#6)





 
This function is from Pytorch Geometric. My guess is that this issue is due to a mismatch in Pytorch Geometric versions. Were you able to use the provided conda environment? If not, which version are you using?

**Comment by EmilyAlsentzer** [comment]
Hi @wangzeyu135798, I just wanted to let you know that I updated the repo so that all of the code should work with the newest version of pytorch geometric. The yml file is updated as well.
