### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by leaf-ygq** [mims-harvard/SubGNN#9]
Hello, thanks for helping me solve last bug about "KeyError"!
When I ran the code last night, I encountered another bug:
TypeError: backward() missing 1 required positional argument: 'optimizer_idx'

![1](https://user-images.githubusercontent.com/75319189/101141914-e491aa80-364f-11eb-9224-558af1013bf7.png)
![2](https://user-images.githubusercontent.com/75319189/101142142-2d496380-3650-11eb-90ca-43d1be9c6b33.png)

Would you mind helping me deal with it?

**Comment by EmilyAlsentzer** [comment]
Hi @leaf-ygq, can you give me a few more details about this issue? Do you always get this error message or only sometimes? It looks like this is a pytorch lightning function that is causing the error. Are you using the same version of pytorch lightning as in the yml file?

**Comment by leaf-ygq** [comment]
Hi @EmilyAlsentzer, I always get this error message. The version of my pytorch lightning is 1.0.8. I installed the conda environment using your yml file, but it seems that the yml file loses some modules which support your code. For example, when I first ran your code, it losed pytorch lightning. So I installed it using command "pip install". Now I check the yml file in your github again, there is no informaion about pytorch lightning. Is there somthing wrong?

**Comment by EmilyAlsentzer** [comment]
Thanks for catching the missing pytorch lightning package in the yml. In creating a pared down yml file, I must have forgotten to include it. I'll upload a new one ASAP, but in the meantime can you try `pip install pytorch-lightning==0.7.1`?

**Comment by leaf-ygq** [comment]
ok, thanks for your help! When I change the version of pytorch-lightning, this problem is solved.
